name: Sanity Serial Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      artifact_name: sanity-serial-test-results
      pytest_marker: "sanity and serial"
      pytest_parallel: 1
      pytest_path: '' # Run tests discovered from the root directory
      pytest_report: sanity-serial-test-results.html
      pytest_reruns: 2
      pytest_variables: prod.json
      python_version: 3.x
